sudo: required

language: bash

services:
  - docker

git:
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

install:
  - wget https://github.com/spf13/hugo/releases/download/v0.15/hugo_0.15_amd64.deb
  - sudo dpkg -i hugo_0.15_amd64.deb

script:
  - hugo
  - docker build -t website-personal .
  - docker run -d -p 80:8080 website-personal; sleep 10
  - docker ps | grep website-personal
  - curl -s -o /dev/null -I -w "%{http_code}" http://localhost:80/ | grep 200
