---
version: '0.1'

environment_variables:
  plaintext:
    AWS_DEFAULT_REGION: 'us-east-2'
    HUGO_VERSION: '0.70.0'
    HUGO_SHA256: >-
      7383dd9e665e776d7080eeb52cf421871e582bb166bba66679c9e0ce259a055d
    HUGO_DOWNLOADS: 'https://github.com/gohugoio/hugo/releases/download'
    HUGO_DOWNLOAD: '${HUGO_DOWNLOADS}/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb'

phases:
  install:
    commands:
      - 'wget --quiet ${HUGO_DOWNLOAD}'
      - 'echo "${HUGO_SHA256}  hugo_extended_${HUGO_VERSION}_Linux-64bit.deb" | sha256sum -c -'
      - 'dpkg -i hugo_extended_${HUGO_VERSION}_Linux-64bit.deb'
    finally:
      - 'hugo version'
  build:
    commands:
      - 'git submodule init'
      - 'git submodule update --recursive'
      - 'hugo --minify'
  post_build:
    commands:
      - 'aws s3 sync --delete public s3://twmartin.codes'
