---
version: '0.1'

environment_variables:
  plaintext:
    AWS_DEFAULT_REGION: 'us-east-2'
    HUGO_VERSION: '0.56.3'
    HUGO_SHA256: >-
      4c7d3dd394e0ea34e353418b81ab8123f07006a529b432436c361cb9d04987ed

phases:
  install:
    commands:
      - 'wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb'
      - 'echo "${HUGO_SHA256}  hugo_extended_${HUGO_VERSION}_Linux-64bit.deb" | sha256sum -c -'
      - 'sudo dpkg -i hugo_extended_${HUGO_VERSION}_Linux-64bit.deb'
    finally:
      - 'hugo version'
  build:
    commands:
      - 'git submodule init'
      - 'git submodule update --recursive'
      - 'hugo --minify'
  post_build:
    commands:
      - 'aws s3 sync --delete public s3://twmartin.codes'
