---
version: '0.1'

environment_variables:
  plaintext:
    AWS_DEFAULT_REGION: 'us-east-2'

phases:
  install:
    commands:
      - 'sudo apt-get update'
      - 'sudo apt-get install hugo'
    finally:
      - 'hugo version'
  build:
    commands:
      - 'git submodule init'
      - 'git submodule update --recursive'
      - 'hugo --minify'
  post_build:
    commands:
      - 'aws s3 sync --delete public s3://twmartin.codes'
