---
version: '0.1'

environment_variables:
  plaintext:
    AWS_DEFAULT_REGION: 'us-east-2'
    HUGO_VERSION: '0.56.3'
    HUGO_SHA256: >-
      e77aafdb1b9c7442a5c4dd32c03443d8ac578cc838704b975686ec0d87797907

phases:
  install:
    commands:
      - 'curl -Ls https://github.com/spf13/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz -o /tmp/hugo.tar.gz'
      - 'echo "${HUGO_SHA256}  /tmp/hugo.tar.gz" | sha256sum -c -'
      - 'tar -xvzf /tmp/hugo.tar.gz -C /tmp'
      - 'mv /tmp/hugo /usr/bin/hugo'
  build:
    commands:
      - 'git submodule init'
      - 'git submodule update --recursive'
      - 'hugo --minify'
  post_build:
    commands:
      - 'aws s3 sync --delete public s3://twmartin.codes'
