baseurl = "https://twmartin.codes"
languageCode = "en-us"
title = "twmartin.codes"
theme = "hallo"
enableRobotsTXT = true

[Author]
  name = "Ty Martin"

[params.colors]
  background = "#4286f4"
  foreground = "#edf7ff"
  hover = "#000000"

[params]
  [[params.links]]
    icon = "github"
    title = "Github"
    url = "https://github.com/twmartin"
  [[params.links]]
    icon = "linkedin"
    title = "LinkedIn"
    url = "https://www.linkedin.com/in/tywmartin/"
  [[params.links]]
    icon = "twitter"
    title = "Twitter"
    url = "https://twitter.com/tmart2011"
  [[params.links]]
    icon = "docker"
    title = "DockerHub"
    url = "https://cloud.docker.com/u/tmart2011"
