---
version: 2

jobs:
  htmlproofer:
    docker:
      - image: 'cibuilds/hugo:latest'
    environment:
      HUGO_BUILD_DIR: 'public'
    steps:
      - run: 'apk update && apk add git'
      - 'checkout'
      - run: 'git submodule sync && git submodule update --init'
      - run: 'hugo -v --minify -d $HUGO_BUILD_DIR'
      - run:
          name: 'run htmlproofer'
          command: >-
            htmlproofer $HUGO_BUILD_DIR
            --check-favicon --check-html --check-img-http --check-opengraph
            --enforce-https --http-status-ignore 999

  markdownlint:
    docker:
      - image: 'circleci/ruby:2.6.3'
    steps:
      - 'checkout'
      - run:
          name: 'install mdl'
          command: 'gem install mdl'
      - run:
          name: 'run mdl'
          command: 'mdl -r ~MD013 README.md'

  tflint:
    docker:
      - image: 'wata727/tflint'
    steps:
      - 'checkout'
      - run:
          name: 'run tflint'
          command: 'tflint'

  yamllint:
    docker:
      - image: 'circleci/python:3.7'
    steps:
      - 'checkout'
      - run:
          name: 'install yamllint'
          command: 'sudo pip install yamllint'
      - run:
          name: 'run yamllint'
          command: 'yamllint ./ .yamllint'

workflows:
  version: 2
  continuous_integration:
    jobs:
      - 'htmlproofer'
      - 'markdownlint'
      - 'tflint'
      - 'yamllint'
