---
version: 2

jobs:
  tflint:
    docker:
      - image: 'wata727/tflint'
    steps:
      - 'checkout'
      - run:
          name: 'run tflint'
          command: 'tflint'

  yamllint:
    docker:
      - image: 'circleci/python:3.7'
    steps:
      - 'checkout'
      - run:
          name: 'install yamllint'
          command: 'sudo pip install yamllint'
      - run:
          name: 'run yamllint'
          command: 'yamllint ./ .yamllint'

workflows:
  version: 2
  continuous_integration:
    jobs:
      - 'tflint'
      - 'yamllint'
