---
name: ci
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  htmlproofer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: setup-hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.54.0'
      - name: hugo-build
        run: hugo --minify
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - name: install-htmlproofer
        run: gem install html-proofer -v 5.0.8
      - name: run-htmlproofer
        run: |
          htmlproofer public/
            --check-favicon --check-html --check-img-http --check-opengraph
            --enforce-https --ignore-status-codes 999 --ignore-urls "https://twitter.com/tmart2011"

  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v15

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install-yamllint
        run: pip install yamllint
      - name: yamllint==1.35.1
        run: yamllint .
